package:
    name: dtw
    version: "{{ load_setup_py_data().version }}"

source:
    path: .

requirements:
    build:
        - numpy <1.15

    run:
        - numpy <1.15

test:
    requires:
        - numpy <1.15

    import:
        - dtw

about:
    home: https://github.com/paul-freeman/dtw
    license: MIT
    license_file: LICENSE
